engines:
 csslint:
   enabled: false
 duplication:
   enabled: true
   config:
     languages:
     - javascript
 eslint:
   enabled: false
 fixme:
   enabled: true
ratings:
 paths:
 - "server/**/*.js"
exclude_paths:
 - "node_modules/"
 - "template/*"
 - "client/"
 - "server/test"